### ISSUE TITLE
This line throws Cannot read property 'key' of undefined on corporate Mastercard mac. 

### ISSUE THREAD

**Issue by krupalghorpade** [Mastercard/insomnia-plugin-mastercard-auth#24]
https://github.com/Mastercard/insomnia-plugin-mastercard-auth/blob/f7121c3edc65d0dc961925119222d4b498e0ea80/src/mastercard-auth.js#L35

**Comment by jaaufauvre** [comment]
Hi @krupalghorpade,

What does "_on corporate Mastercard mac_" mean?

Please describe a scenario for us to reproduce the error on a regular mac machine.

If you can't, please solve this issue with your IT department.

Thanks!

**Comment by krupalghorpade** [comment]
I'm a MC employee. Looks like if consumer key is wrong, it throws ```Cannot read property 'key' of undefined``` error.

**Comment by jaaufauvre** [comment]
Hi @krupalghorpade,

This is not enough information for us to reproduce the issue. Can you please provide a full reproduction scenario as requested earlier? In addition to the test data and steps, don't forget to mention the versions of Insomnia, macOS and of the plugin you use.

If you already identified the issue is caused by restrictions on a corporate machine, please solve this issue with your IT department.

Thanks!

**Comment by ade90036** [comment]
That's a generic JS error.

Mac / Linux / Windows / Solaris / Corporate / Non corporate doesn't have
anything to do with it.

The code is trying to access a value from a map which was not properly
initialised

Please check SDK initialisation code / documentstion
